### PR TITLE
Add Fancy Trakt PIN Auth dialog

### PR DESCRIPTION
**Pull request by tknorris**
Here's the SALTS PIN Auth Dialog applied to script.trakt. 

Note, The window has a Remind Me Later button, so I added a check on idle to pop the window up if there's no auth info and it's either never popped up before or you've asked to be reminded later.

I did several different tests and everything seems to work well. I explicitly tested to make sure a Kodi restart is not required for the authorization to take effect.

I didn't change it, but we might want to consider rewording the "Where can I find my PIN?" setting to be something like "How do I authorize the trakt addon to access my trakt.tv account?". I'm not sure noobs will know what that means..Let me know if you want me to change it.

### CODE REVIEW

**Comment by Razzeee** [comment]
I'm gone for the weekend,  won't have the time to check this before Monday.

**Comment by Razzeee** [comment]
Can you remove the strings from the old dialog? 

Also we might want to split up 32157 as some translators might break the link formating

**Comment by tknorris** [comment]
Sure will.

**Comment by tknorris** [comment]
Commit added to split the string and to remove the old unused strings

**Comment by Razzeee** [comment]
I'm really loving this implementation. Just because I was thinking about it the other day, can you think of a way to display a readonly value in the settings? 
I would like to display the username of the authorized user, it's confusing for me as I use a test account and my normal one. And it's probably also nice for everyone else.

**Comment by tknorris** [comment]
Yes, you can do that. you add a text setting with visible="true" and enable="false". Then it will show the current value, but it won't be editable.

**Comment by s7eele** [comment]
fwiw that sounds cool

**Comment by tknorris** [comment]
Let me know if/when you want to do another beta.

**Comment by Razzeee** [comment]
@tknorris 
we're missing the string for 32147 can you le me know what it should be?

**Comment by tknorris** [comment]
Hmm. Weird. I thought I checked all those. The string is "Trakt.tv PIN Authorization Failed" but let me double check that I didn't make some other mistake when I was moving strings around.

**Comment by tknorris** [comment]
Ahh, I see now. I removed 32147 accidentially when removing the unused strings and then didn't test again. The string I gave you is the correct one.

**Comment by Razzeee** [comment]
When I talked about splitting the strings I mostly ment this one:
"1) Visit [COLOR skyblue]http://trakt.tv/pin/999[/COLOR] or scan the QR Code below."

As I can see some translators breaking the format etc. I'll try to move this to the codebase. Also the url shouldn't be up for a translator to decide upon.

**Pull request merged**
