### PR TITLE
Fix for duplicate episode watched status sync

### PR DESCRIPTION
**Pull request by tknorris**
I checked to see if kodiRpcToTraktMediaObject was called for tv shows from anywhere else and I don't think it is. So, we should be good. I tested on my main htpc to make sure this stopped the duplicate syncs.

### CODE REVIEW

**Comment by Razzeee** [comment]
Good that we got this catched in the beta.
I'm ot really sure, but perhaps we might also want to add a 'isSeason'?

**Comment by tknorris** [comment]
That would probably be a good idea. I'm about to go afk though so I'll have to push a beta later.

**Comment by Razzeee** [comment]
Pushed that additional change. Go ahead when your ready!
And thanks!

**Comment by tknorris** [comment]
3.0.2~beta4 pushed for this fix.

**Pull request merged**
