### PR TITLE
skin update

### PR DESCRIPTION
**Pull request by ronie**
- updated texture
- bigger font for the code text
- cleanup xml files

### CODE REVIEW

**Comment by Razzeee** [comment]
Thanks @ronie 
Really appreciated

**Comment by freeman212** [comment]
noticed something odd in the top left corner of the background image. 

was this change intended ?

**Comment by ronie** [comment]
heh, glad at least someone has an eye for detail ;-)

will fix, thx for the heads-up!

**Comment by ronie** [comment]
https://github.com/Razzeee/script.trakt/pull/248

**Comment by freeman212** [comment]
@ronie no worries, mate ! thanks for the quick fix

**Pull request merged**
