### PR TITLE
PinAuth dialog design

### PR DESCRIPTION
**Pull request by vonH**
Updated PinAuth dialog, textures, and fanart image.

### CODE REVIEW

**Comment by razzeee** [comment]
Why the change for the fanart? The old one tried to mimic that graphic that was used in trakt itself

**Comment by razzeee** [comment]
After manually merging it, it doesn't seem right. Probably something merged wrong? Can you post how it should look?
pinauth

**Comment by razzeee** [comment]
Nevermind, I've found the problem

**Comment by razzeee** [comment]
Merged here https://github.com/Razzeee/script.trakt/commit/f4860c83b65a7a634dfee200119315c67f2184d4
Minus the new fanart

**Comment by vonH** [comment]
Yep, I removed an unneeded string. It's pretty obvious what the screen is for :)

**Pull request closed without merging**
