### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by s7eele**
here it is finally, i think its good, a lot of the same changes i made to your post draft

appreciate you letting me get some practice here, completely understand if this ends up just being cancelled

### CODE REVIEW

**Comment by Razzeee** [comment]
Looking waterproof to me.
The only thing I would not change is 
```
Enter your **username** and **password**, change any other settings as needed
```
But that might be due to me beeing a developer, so to me it's clear that there is an and between each of the statements ;)

**Comment by s7eele** [comment]
i can make that change real quick no problem, i ask because im not yet sure if you can accept certain parts of a pr and deny others, i would probably find out if i just waited but im impatient, do i have any action here?

**Comment by Razzeee** [comment]
No all is good and it is merged. Your wording might in fact be the clearere one for real world users.

**Comment by s7eele** [comment]
i made this whole deal a lot harder than it really is, as usual lol

**Pull request merged**
