### PR TITLE
pep8 cleanup

### PR DESCRIPTION
**Pull request by tknorris**
Here's the pep8 cleanup. I made sure not to make any logic changes here to avoid hard to track down issues.

Note, I exclude a few pep8 recommendations when I run the pep8 checker that I think are a little over the top. The ones I exclude are: E501,E302,E701,W293. You can see what each check is here: http://pep8.readthedocs.org/en/latest/intro.html#example-usage-and-output

The one thing I didn't change was in sqlitequeue.py and utilities.py there are LOTS of assignment to reserved words like "file", "id", "list", etc. Let me know if you want me to clean those up as well. They are somewhat dangerous as they can cause hard to track down issues where the variable hides the keyword or vice versa.

Once you merge this, I'll pull it back down and push out a new beta.

### CODE REVIEW

**Comment by Razzeee** [comment]
I would really like to change these variable names, but it might be pretty hard to find other good names for them. Hiding variables is never a good thing.

**Comment by Razzeee** [comment]
Well checked the docs and would really like to include E501,E302,E701,W293. Shouldn't harm and I actually like the rule of E501

**Comment by tknorris** [comment]
Before I actually enable E501, I just want to point out that there are hundreds of lines that exceed that limit. Are you sure you want all of those changed? I don't know about you, but my editor width goes far beyond 82 chars that's why I disable it.

On E302, the code currently uses 1 space between functions but you want to make it 2 everywhere? Again, just double checking.

**Comment by Razzeee** [comment]
Well maybe it's not a good idea. Yes my editor is probably broader, but I can understand the need. 
What's braking the deal for me is probably that the history could get pretty messy. 

On E302: Spaces? I thought new lines. And to be honest I don't care if it's one or two. So just leave it :)

**Comment by tknorris** [comment]
Yep, it's blank lines. I updated the PR for 701 and I didn't see any W293 errors, so I think the code is all cleaned up. Should be ready to merge when you are.

**Comment by Razzeee** [comment]
So do I need to check if it's still working or have you done some basic checks?

**Comment by tknorris** [comment]
A beta should be enough. I didn't test anything yet but all the changes were automated except for a couple of minor variable name changes for unused vars in a couple of loops.

**Comment by s7eele** [comment]
does the context menu show up like it did in the last version still, i still cant see it after installing latest dev branch and latest module.trakt but figure im doing something wrong

**Comment by Razzeee** [comment]
I did some basic tests and my sync was successful and nothing was suspicious

@s7eele it should work as before, but just with the dev version of my repo, no other.

**Comment by s7eele** [comment]
thx @razzeee, i think im just doing something wrong, im gonna try one more time,downloading latest -dev and module.script.trakt and overwriting directories, however i dont want to waste your time so no worries, i can wait for beta release through tk's repo, it is a bit aggravating as it shouldnt be that difficult :-/

**Pull request merged**
