### PR TITLE
Continuing the interface calls.

### PR DESCRIPTION
**Pull request by marcoamador**
Continued the code on the interfaces from where you left it. Hope it can save some time.

Also, I think you had a little bug in the rating calls (an additional comma in two of them).

Keep up the good work!

### CODE REVIEW

**Comment by fernandog** [comment]
@marcoamador can you send some prints of the new interface? thanks!

**Comment by Razzeee** [comment]
@marcoamador 
thank you!

can you please do the pull request on the trakt.py repo (dev tree) https://github.com/fuzeman/trakt.py/tree/develop
as that is the correct place for the updates :)

**Comment by marcoamador** [comment]
Oh, nice. So that means you're not using that library, but instead calls to somewhere else? Is there any matter that I can help you with?

**Comment by Razzeee** [comment]
@marcoamador 
Iam using that library, but we should update it centrally so that the plex users also benefit from our work. So you should commit your work to that develop tree mentioned above.
If it gets added there I will update our version and so on.

**Comment by marcoamador** [comment]
Sure. Will do. :)

**Pull request closed without merging**
