### PR TITLE
id's "fix" for ratings pre-fetch

### PR DESCRIPTION
**Pull request by tknorris**
Submitting this PR just to get it on the books that there's an issue with ratings when playing from an addon that doesn't set script.trakt.ids. The code below throws an exception because curVideoInfo doesn't have an 'ids' key at that time. What I'm not sure of yet is the best way to make it work. This change avoids the exception but doesn't fix the ratings issue...I'll continue to think about it...

### CODE REVIEW

**Comment by tknorris** [comment]
Note also, even with this change if the movie doesn't have an imdb or the show doesn't have a tvdb, we'll still get an exception...

**Comment by tknorris** [comment]
Noticing that this code path only occurs if 1) Scrobbling is turned off for this media type 2) Your are playing from an addon 3) That addon doesn't set a script.trakt.id's property. I can't seem to find an easy way to actually make the ratings pop-ups work in this case. All the ratings calls need some kind of id to work properly. I think we might be better off just improving this part of the code to work with any of the id's but to require at least one of them...

**Comment by tknorris** [comment]
OK, these latest changes should make ratings work when scrobbling is off and playback is from an addon as long as the addon provides an "ids" object with at least one id.

The only problem case is if the provided id's object only gives a tmdb value for a tvshow which is technically possible though not likely. In this case, the getShowSummary() will treat the tmdb value as a tvdb which obviously won't work. The only way I saw to fix this is to id_type to the getXSummary calls.

As I mentioned, I don't see a straightforward way to make non-scrobbled ratings work with just a title & year. The only option I see is to add the search API to traktapi and use that to lookup the id's for the title/year. That's effectively what the title/year scrobble does anyway.

**Comment by Razzeee** [comment]
You need to convert the id first, we already do this somewhere. Have a look at the utilities there is a class that diagnose what id your giving. Check the usages, we then call the lookup method in the trakt api to get the right ids

**Comment by tknorris** [comment]
I looked at that, but the problem was it wouldn't help because the showsummary doesn't take an id_type anyway so knowing what you have doesn't help. Also, that function wouldn't help because it would id the tmdb as tvdb since it's a tv show...

**Comment by tknorris** [comment]
I suppose we could do an id lookup in the case where the best id for a tvshow was the tmdb id, and then switch the best id to the resulting trakt id. I'm really not sure it's worth coding for though. It's such an one off case I can't imagine it even ever happening.

**Comment by Razzeee** [comment]
well looking up the trakt id was what I was talking about, so that should sort it out

**Comment by tknorris** [comment]
I added the mapping of tmdb for shows to something else. It also requires a small change to script.module.trakt which I'll submit via PR in a sec.

**Comment by tknorris** [comment]
Note, I still think the old code was better. Let me know if you want to revert this latest commit.

**Comment by Razzeee** [comment]
Why are you only doing this when this is a tmdb id?

**Comment by tknorris** [comment]
Because that's the only time its an issue.

**Comment by tknorris** [comment]
Otherwise the TV summary call will guess the right   id type.

**Comment by tknorris** [comment]
Reverted the id lookup changes. This should be mergeable now.

**Comment by Razzeee** [comment]
Can you squash this?

**Comment by tknorris** [comment]
you bet...

**Comment by tknorris** [comment]
done.

**Pull request merged**
