### PR TITLE
[fanart] new fanart

### PR DESCRIPTION
**Pull request by vonH**

### CODE REVIEW

**Comment by Razzeee** [comment]
No blur? 






:P

**Comment by Razzeee** [comment]
Hrm, thinking of this, it might be causing an copyright issue?

**Comment by vonH** [comment]
The current one could also create a copyright problem, actually the entire trakt website could create a copyright problem :8ball:

**Comment by Razzeee** [comment]
!http://i.giphy.com/ElEuOb8NDFWiQ.gif!

**Pull request merged**
