### PR TITLE
Fix init; make pin visible

### PR DESCRIPTION
**Pull request by tknorris**

### CODE REVIEW

**Comment by Razzeee** [comment]
```
FATAL: [script.trakt] __main__: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'ValueError'>
                                            Error Contents: ('Expecting property name: line 1 column 2 (char 1)',)
                                            Traceback (most recent call last):
                                              File "C:\Users\razze\AppData\Roaming\Kodi\addons\script.trakt\default.py", line 18, in <module>
                                                traktService().run()
                                              File "C:\Users\razze\AppData\Roaming\Kodi\addons\script.trakt\service.py", line 95, in run
                                                globals.traktapi = traktAPI()
                                              File "C:\Users\razze\AppData\Roaming\Kodi\addons\script.trakt\traktapi.py", line 31, in __init__
                                                self.authorization = loads(getSetting('authorization'))
                                              File "D:\Kodi\system\python\Lib\json\__init__.py", line 338, in loads
                                                return _default_decoder.decode(s)
                                              File "D:\Kodi\system\python\Lib\json\decoder.py", line 366, in decode
                                                obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                              File "D:\Kodi\system\python\Lib\json\decoder.py", line 382, in raw_decode
                                                obj, end = self.scan_once(s, idx)
                                            ValueError: Expecting property name: line 1 column 2 (char 1)
                                            -->End of Python script error report<--
```
Getting this right now

**Comment by tknorris** [comment]
that's weird. it's working fine here. let me restart kodi to be sure.

**Comment by Razzeee** [comment]
@tknorris 
I got it fixed

**Comment by tknorris** [comment]
I committed a fix as well, just junk it if you don't need it.

**Comment by tknorris** [comment]
Whoops, I see you committed yours already. I'll just pitch mine. Note you missed on setSetting() in on_token_refreshed

**Comment by Razzeee** [comment]
Yeah, I already check it vs yours. It's commited.

**Comment by tknorris** [comment]
Cool. Let me know when you want to push a new beta.

**Comment by Razzeee** [comment]
Let's go!

**Comment by tknorris** [comment]
3.0.1~beta7 pushed.

**Comment by s7eele** [comment]
that was quick, glad i checked back, i was still looking through log lol

**Pull request merged**
