### PR TITLE
Fix to show ratings

### PR DESCRIPTION
**Pull request by tknorris**
getIdLookup seems to just return a raw Show object when there is an exact match so your [0] was failing:
```
16:40:20 T:2817518400   FATAL: [script.trakt] service: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'TypeError'>
                                            Error Contents: ("'Show' object does not support indexing",)
                                            Traceback (most recent call last):
                                              File "/home/tknorris/.kodi/addons/script.trakt/service.py", line 61, in _dispatch
                                                self.doManualRating(ratingData)
                                              File "/home/tknorris/.kodi/addons/script.trakt/service.py", line 150, in doManualRating
                                                imdb = dict(globals.traktapi.getIdLookup(data['imdbnumber'], id_type)[0].keys)['imdb']
                                            TypeError: 'Show' object does not support indexing
                                            -->End of Python script error report<--
```
Also, what do you think about changing this logic to just always map to imdb # first and then make the summary / rating calls? In particular, I'm worried that the trakt API doesn't allow tmdb and tvdb id's for summary calls...

### CODE REVIEW

**Comment by tknorris** [comment]
(Note, if it wasn't clear, I was suggesting I can make those changes. I just didn't want to mess with your changes without getting your opinion first)

**Comment by Razzeee** [comment]
I'm not sure I'm getting the things you want to do.

We're calling the lookup method to convert the tvdb id or whatever to a imdb id and then call the summary with it. It might actually be a lot safer to use the trakt id.

**Comment by tknorris** [comment]
What I'm suggesting is for all the media types, not just show, to convert the passed id (of whatever type) to imdb regardless of what we start with and then use that for all the summary & ratings lookups rather than passing whatever type comes in. Converting to trakt ID would work as well.

**Comment by Razzeee** [comment]
Well yeah thats the idea go ahead.
I wanted to do that but I figured we first need to convert the id in the "imdbnumber" field for episodes and series to the real imdb number of that show. Not sure if you remember that problem

**Comment by tknorris** [comment]
Hmm, the problem might be that you didn't make all the changes you meant to because for episodes, seasons, and movies we are still passing whatever came in from upstream for the summary calls. Which in the Kodi case isn't the imdbnumber (even though we call it that). Regardless, I'll go ahead and make the changes I intended and just let me know if you don't like them.

**Comment by Razzeee** [comment]
Well are you trying to convert the id for the series and episode also?
I basically stopped there and just did the change to the ones where I was sure it would work.

**Comment by tknorris** [comment]
we'll have to convert them otherwise they won't work from kodi and nor will the movies from kodi...They work from addons because we pass in the imdb number, but with that weird kodi bug where we ask for imdbnumber but we get back tvdb/tmdb number nothing will work.

**Comment by Razzeee** [comment]
I don't think it's a bug (unfortunatly)
But movies and series should be okay. The logic in place should convert to the right one, do a lookup and do summary and rating calls.
But we need to resolve the "imdbnumber" on episodes and series to the show_imdbnumber if you might call it that.

**Comment by tknorris** [comment]
OK, latest commit added should fix all the various ways of doing manual ratings. I tested it with both Library and Non-Library manual ratings for Movies, Shows, Seasons, and Episodes. (Note previously manual ratings didn't work on Library Seasons at all.)

A nice side effect of this change is remoteid no longer has to be imdb. It can be imdb, tvdb, or tmdb. I map whatever is passed to be trakt id. We might want to consider adding an optional attribute to the rating call to specify the id_type so that we can include trakt id and slug as options as well.

**Comment by s7eele** [comment]
you guys have been busy, sounds awesome

**Comment by Razzeee** [comment]
Awesome work, thank you!

**Pull request merged**
