### PR TITLE
clean transparent logo

### PR DESCRIPTION
**Pull request by freeman212**
cleaner icon, making the background completely transparent. cheers and keep up the good work! :+1:

### CODE REVIEW

**Comment by Razzeee** [comment]
@freeman212 
thank you! 
let's hope we get one in 512x512 in the future

**Comment by Razzeee** [comment]
@freeman212 @rectifyer 
maybe one of you has an idea for a fanart (I have no graphical skills)
http://kodi.wiki/view/Add-on_structure#fanart.jpg

**Comment by Razzeee** [comment]
Nevermind, will use this one.
https://github.com/tamland/trakt-sync/blob/master/fanart.jpg

**Comment by freeman212** [comment]
this one is perfect! :+1:

**Pull request merged**
