### PR TITLE
clean transparent 512x512 logo

### PR DESCRIPTION
**Pull request by freeman212**
again a bit cleaner version of the trakt logo with decent 512x512 resolution ;-)

### CODE REVIEW

**Comment by Razzeee** [comment]
@freeman212 
can you compare it with the one I checked in a few hours ago? just pushed it now, not sure which is better

**Comment by freeman212** [comment]
the one I submitted doesn't have those black borders and looks a bit more polished: https://github.com/Razzeee/script.trakt/pull/12/files
if you choose "onion skin" to compare the 2 icons and then drag the slider you can clearly see the difference ;-) I'm glad I can somehow contribute to this project to get our beloved trakt addon back on track, but I'm not a huge python guy.. so this is the least I can do.

**Comment by Razzeee** [comment]
@freeman212 
never written python before I took this on myself ;)

**Comment by s7eele** [comment]
i thought that was something i could do, lol, im desperate to help in any way i can, feel like a freeloader

@Razzeee i left a question on trakt forum for u, should i open an issue for the .strm thing or do u feel that its 'out of scope'

**Comment by Razzeee** [comment]
@s7eele 
just open an issue, but it might be unfixable and very low in priority.

**Comment by s7eele** [comment]
roger that, ill make sure i gather as much info as i can before opening

**Comment by freeman212** [comment]
@Razzeee so you didn't have proper python skills before starting this project? wow maybe I should start learning python too, that's a huge motivation for sure :)

**Comment by Razzeee** [comment]
@freeman212 
yes, never written python before. probably read a few lines here and there over the years. Probably still have very bad python skills.
But I'm a developer in my daytime job, using c# and database stuff and things ;)

**Comment by freeman212** [comment]
@Razzeee well than that's a different starting point ;-) hope I am able to this too one day for a living.. currently planning to study web application development in the near future :)

**Pull request merged**
