### PR TITLE
Added license information

### PR DESCRIPTION
**Pull request by NEOhidra**
Needed to automatically fill the links on http://kodi.wiki and http://addons.kodi.tv/ sites.

### CODE REVIEW

**Comment by razzeee** [comment]
@rectifyer any opinion on which license we can use?

**Comment by rectifyer** [comment]
@Razzeee MIT is usually pretty open, maybe its worth switching to that?

**Comment by razzeee** [comment]
From a quick search I actually think the GNU seems better.

**Comment by razzeee** [comment]
Thanks @NEOhidra

**Comment by tudorplumb** [comment]
stop

------ Original Message ------

**Comment by tudorplumb** [comment]
ask someone else

------ Original Message ------

**Comment by razzeee** [comment]
?

**Pull request merged**
