### PR TITLE
[skin version] 0.10.5

### PR DESCRIPTION
**Pull request by vonH**
Replacement default skin to reflect trakt's new design and logo.

### CODE REVIEW

**Comment by Razzeee** [comment]
Thank you very much! Really appreciating it!

**Comment by s7eele** [comment]
cant wait to try it out, thx

**Comment by Razzeee** [comment]
@vonH 
can you have a look at the dialog window again? For some reason the text on the white background is not that easy to read for me. Not really sure if it's due to the shadow doubling it up or something.
Could that be caused by the skin? I read somewhere that the skin is setting the font, I'm using amber at the moment.

**Comment by vonH** [comment]
Yep, the skin uses fonts from skins, can you try another skin and see if it
looks the same? Screenshots would be helpful. Sent from phone.

**Comment by Razzeee** [comment]
I made a photo of it. http://i.imgur.com/wfXhXba.jpg
Thought it might be my television - pretty dumb in retrosepctive

**Comment by vonH** [comment]
Yep, that shadow is causing issues. Does it only appear like that on Amber? (Using a PC now)

**Comment by Razzeee** [comment]
Not really sure, as I'm using confluence for development, will try some skins and post screenshots soon. It's likely that we can't make it fit for all.

**Comment by vonH** [comment]
We can, by removing the shadow and making the text darker so it stands out more. But, if it's only happening with Amber, then it'll need a rethink. Either way - more screenshots when you have time :)

**Comment by Razzeee** [comment]
So it really seems to be just amber
http://imgur.com/a/CCtam#10

Another "funny" thing to me is that changing the font in the skin settings, didn't change anything at all in the dialog. But that might be normal for someone that knows how skins work.

**Comment by vonH** [comment]
The skin uses the default fonts from Confluence. It's best a skinner
integrates the dialog into their skin, this way custom skin fonts etc can
be used.

**Comment by Razzeee** [comment]
Don't get that. Why is every font in every screenshot different then? Is it just size, shadow, etc on the same font?

**Pull request merged**
