### PR TITLE
Allow to unrate an item on Trakt

### PR DESCRIPTION
**Pull request by razzeee**
FYI @bubblesaddon

### CODE REVIEW

**Comment by razzeee** [comment]
Closes #372

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
Thanks. Appreciated.

**Comment by ghost** [comment]
Will you be releasing a new version of the addon for this change? Or should I make my own alpha version (3.1.11~alpha)?

**Comment by razzeee** [comment]
I'll try to find some time and prepare a new release.

**Pull request merged**
