### PR TITLE
Hide notifications when playing video

### LINKED ISSUE #544: Sync notifications showing when playing even when you choose to hide
## Expected Behavior
When the option to "hide notifications during playing" is on the addon shouldn't notify when hes syncing tvshow/movies and you are watching tvshows/movies

## Current Behavior
Even whit "hide notifications during playing" marked when its syncing the notification occurs when playing tvshows/movies

## Steps to Reproduce (for bugs)
1. Enable sync collection on lib update/cleaning
2. Enable show sync notifications
3. Enable Hide notifications during playback
4. Update your library
5. Run any tvshow/movie

## Context
The notification when its sycing trakt is useful, but its not good having them when watching videos

## Your Environment
* Version used: 3.4.2
* Kodi version used: 18.9 and 19
* Operating System and version: Windows and Android

### PR DESCRIPTION
**Pull request by riksmith**
closes #544

### CODE REVIEW

**Comment by razzeee** [comment]
Thank you, seems sensible

**Comment by riksmith** [comment]
@razzeee  what does the process to get this merged and released look like?

**Comment by razzeee** [comment]
I need to find time to test it

**Comment by riksmith** [comment]
Ok, no problem.

**Pull request merged**
