### PR TITLE
Text Query API Uses

### PR DESCRIPTION
**Pull request by ineffablebob**
Added the Trakt text query API for searching, used in two places:
1. If scrobbling an episode of a show initially fails, make a call to the
Text Query API using the show title. Unlike scrobbling, Text Query will
find alternative titles. If it returns something, try scrobbling again
with the result.
2. Lookup of MythTV PVR recordings, using the recording label to feed the Trakt text search API

Also added some debug logging in the scrobbler,  to make it more clear when there is not enough information.

### CODE REVIEW

**Comment by Razzeee** [comment]
Hrm, well you should just rebase onto this branch, with your three commits.
If that is something, you have no experience with, just let me know and I will cherry pick your changes.

**Comment by ineffablebob** [comment]
Yeah, I'm afraid I'm fairly new to git. Never used rebase before.

**Comment by Razzeee** [comment]
Are you using a frontend or just plain git bash? If your using tortoise git, I might be able to help.
Otherwise, just let me cherry pick.

**Comment by ineffablebob** [comment]
I'm just using the basics from github - Git Desktop and bash. I think I figured it out, though. Check the pull's changed files, I believe I've synced up everything you had so that the only things that show up are my changes.

**Comment by Razzeee** [comment]
No, unfortunately not. This won't be solveable without a rebase and a force push.

**Pull request closed without merging**
