### PR TITLE
Use decode to remove unicode errors

### PR DESCRIPTION
**Pull request by mattsch**
Was getting a decode error on sync:
                                              File "/storage/.kodi/addons/script.trakt/utilities.py", line 272, in findInList
                                                if unicode(key_val) == unicode(kwargs[key]):
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\xb3' in position 5: ordinal not in range(128)

This fixes that problem and sync was able to complete on my system.

### CODE REVIEW

**Comment by BenEfrati** [comment]
Hi, 
I encounter the same problem. tried your fix but got this error:
File "C:\Users\**\AppData\Roaming\Kodi\addons\script.trakt\utilities.py", line 272, in findInList
                                                if key_val.decode('utf-8') == kwargs[key].decode('utf-8'):
                                            AttributeError: 'int' object has no attribute 'decode'

**Comment by mattsch** [comment]
Hrm, guess in some cases that will be an int instead of string, I'll update it once my machine is free.

**Comment by Razzeee** [comment]
@mattsch & @BenEfrati 
please try the new version first, was already mentioned by 
https://github.com/Razzeee/script.trakt/pull/3#discussion_r23496147
and could have been fixed by this, we just need validation
https://github.com/Razzeee/script.trakt/commit/049cf4cd8914e08e8d297b233442b7078a6c4751

**Comment by mattsch** [comment]
Hrm, I swear I tried using unicode() first and it failed, but that's working now for me.  I'll close this one.

**Pull request closed without merging**
