### PR TITLE
add id scrobbling

### PR DESCRIPTION
**Pull request by tknorris**
This adds the code to pick up the script.trakt.ids property and pass it to scrobble if it exists. It also adds to the title/year fallback setting (default = True). I tested movies and episodes with script.trakt.ids set and not set.

### CODE REVIEW

**Comment by Razzeee** [comment]
Seems okay code wise, can you write a wiki page for the part where you provide it in your addon?
So that I can add it to the wiki?

**Comment by tknorris** [comment]
Sure. I'll add a wiki to my repo and write a paragraph on it there.

**Comment by tknorris** [comment]
Proposed page here: https://github.com/tknorris/script.trakt/wiki/Providing-id%27s-to-facilitate-scrobbling

**Comment by Razzeee** [comment]
Looking good. Maybe add an list after the part with only one id needs to be set, like:
From best to worst: Trakt id, trakt slug, all other ids

**Comment by Razzeee** [comment]
Also can you add an entry to the changelog and do another beta?

**Comment by tknorris** [comment]
Wiki page updated. I'll update the change log and push a  beta  shortly.

**Comment by Razzeee** [comment]
Thanks

**Pull request merged**
