### PR TITLE
Sync collection on library clean.

### PR DESCRIPTION
**Pull request by anaconda**
Pretty trivial and self-explanatory.

### CODE REVIEW

**Comment by Razzeee** [comment]
This should probably have a setting of its own. Not really sure what the usecase is

**Comment by anaconda** [comment]
I have always interpreted the "Sync collection on library updates" setting as "Sync collection automatically", as there are already 2 settings for the content ("Add movies to trakt", "Add episodes to trakt"). So I think that setting is applicable here too (however, I'd change it to "Sync collection automatically"). I think this add-on has too many settings already.
There are also 2 settings for configuring collection cleanup ("Remove episodes", "Remove movies") which are honored here.

As for the use case - I wanted this because I delete episodes after watching and I want my trakt collection to always reflect what's in my Kodi library, but to remove them from trakt I always need to manually start a library scan (pointless, as there's nothing to scan) or start a manual sync (it shows the progress bar and may be pretty slow if the trakt API is always reporting errors, like it's doing since yesterday).
I use the watchdog add-on which starts a library clean automatically when a video file is deleted: that means an "on clean" event is generated and my trakt now is always reflecting what's currently in my library without manual intervention.

**Comment by Razzeee** [comment]
@anaconda 
nice, will merge this soon, but I might edit the settings string to something like "Sync collection on library update or cleaning"

**Comment by anaconda** [comment]
Updated - however, I think "Sync collection automatically on library changes" sounds better.

**Comment by anaconda** [comment]
Totally off topic here, but as the API was slow as hell this night I have noticed that the rating dialog after having watched an episode was only shown after a noticeable delay (5-10 seconds). I have scrobbling and rate-after-watch enabled.
I was able to track it down to:
https://github.com/Razzeee/script.trakt/blob/dev/scrobbler.py#L222
which in turn is caused by:
https://github.com/Razzeee/script.trakt/blob/dev/scrobbler.py#L255
(i.e. it seems scrobbling doesn't use an asynchronous queue, so it's blocking if the API is continuously reporting internal errors.)

**Comment by Razzeee** [comment]
@anaconda
yeah, there are probably quiet a few things more that should be async
and yes, I too think yours sounds better, but it's missing the info. We are both skilled with kodi and know what will happen, but we need to be transparent, as the user won't be sure, whats happening and why.

Btw @your commit affecting the headers

```
if sys.version_info >=  (2, 7):
    import json as _json
else:
    import simplejson as _json 
```
should be the way accoring the the kodi forum. will fix this in all classes in the next days.

**Comment by anaconda** [comment]
> and yes, I too think yours sounds better, but it's missing the info. We are both skilled with kodi and know what will happen, but we need to be transparent, as the user won't be sure, whats happening and why.

Fair point - I can agree on this :+1:

> Btw regarding your commit affecting the headers

Sorry, I wasn't clear enough in the commit message. It was only a cleanup commit, everything was working fine - it's just that I find it confusing to not sort imports (first by where we're importing from and then alphabetically) :-).
Btw in Helix the try-simplejson-except-json won't work. Only the Python standard library and dependencies declared in the addon.xml file will be added to the Python module search path. Apart from that, simplejson is declared as a dependency in addon.xml (script.module.simplejson) so it'll always be available (assuming people use "Install from zip" as it'll install dependencies).
I have removed that part completely because it's not used in service.py.

**Comment by Razzeee** [comment]
Merged, thanks for your work!

**Comment by Razzeee** [comment]
not sure if this is an sideeffect. if you clean your library and it performs a silent trakt sync. You can try to do a manual sync after that, but the progress won't show up, and it seems like the sync fails.

**Pull request merged**
